# Generated by Django 4.1.5 on 2023-02-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='User',
        ),
    ]
