# Generated by Django 4.1.5 on 2023-02-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
